name: The Bitcoin Trader Guide
favicon: null
layout_spectrum: 0.23973
typography_spectrum: 0.5
title: The Bitcoin Trader Guide
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#03fc60'
    - '#d39104'
    - '#055724'
    - '#e1d600'
  brandStrength: 0.5
  lightness: 0.9227051564957947
  saturation: 0.4811018821783364
  rhythmicContrast: 0.3851640827488154
purpose: []
